### PR TITLE
Add pdb4amber to ambermini

### LINKED ISSUE #29: pdb4amber?
Does `pdb4amber` get installed with ambermini?  I don't see it getting put into the path.

### PR DESCRIPTION
**Pull request by swails**
Closes #29 

I don't know that this is necessarily going to work with Windows, though...  Does a suffix-free Python script need to have .bat appended to its name?  Would adding `$(WRAPPER_SFX)` to the end of `pdb4amber` fix the problem? (mostly a question for @rmcgibbo, since I recall he gave me some advice regarding ParmEd and Windows).

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks, @swails!

**Comment by swails** [comment]
No guarantees for Python 3.  I only checked that it built and gave the help message -- not that any of the operating modes worked.  It *should* be fine, but my disclaimer is only Python 2 is tested :).

**Comment by jchodera** [comment]
Awesome!  Let's wait a bit to see what @rmcgibbo says about windows.

**Comment by swails** [comment]
Yea, it's definitely not right for Windows yet.  I've seen some potentially helpful information about Windows here: https://matthew-brett.github.io/pydagogue/installing_scripts.html

But I have absolutely zero patience for Windows, so I'm not putting any effort into it.

**Pull request closed without merging**
