### PR TITLE
Attempt AmberTools v16 upgrade

### PR DESCRIPTION
**Pull request by Lnaden**
Making first pass at upgrading to AmberTools 16 to address #36.

Following what @swails did for v15, I pulled the AmberTools16 tarball and updated existing files while trying to copy over new ones with Meld. I should have preserved the custom changes needed to make this a standalone.

As noted in the commit, there are a few known outstanding issues

* New antechamber functions `match_atomname` and `equation2`. Not sure if those need private calls as `antechamber` and `parmchk` do

* There are a number of FF files which were renamed or flat removed in the new AmberTools16. we need to decide what to do with them to minimize bloat and keep consistent with filenames.

* No tests have been run, need to figure out what that looks like

### CODE REVIEW

**Comment by Lnaden** [comment]
@swails I attempted to convert to AmberTools 16 following your suggestion in #36. Any input you can provide to see if I missed something would be appreciated. 

Do you also have ideas on how to test this to make sure I upgraded it correctly? Thanks!

**Comment by Lnaden** [comment]
Just an update. Started trying to get the tests working, looks like I will have to fix some of the pointers in the tests themselves to make it work correctly.

**Comment by Lnaden** [comment]
This PR is almost done. Any feedback people want to provide for it would be welcome at this time!

The remaining bugs with this repo are git issues I'm working through (a number of files are not being cloned sometimes). Anyone have an idea why that might be happening?

Change log:
- Updated to AmberTools 16 FFs
- Compiling new program `paramfit` tool into AmberMini.
- Added complete tests for `antechamber`, `leap`, `sqm`, and `paramfit`.
- Added documentation to explain process of updating this repo in the future
 * Including how to make standalone binaries needed for AmberMini

Outstanding Issues:
- `git clone`/`git checkout` seems to be missing files sometime.
- Appveyor is not getting its `mingwpy` compilers, not related to repo stability.

**Comment by Lnaden** [comment]
This PR is ready, baring appveyor fixing if we want to bother with that.

We may want to do a couple versioning things before merge

**Comment by swails** [comment]
I haven't been following this that closely, but it does not seem like a sustainable model going forward... 

When I was doing it it wasn't all that sustainable, and this update looked a LOT more painful.

What is the plan looking forward?

**Comment by jchodera** [comment]
Migrate away from ambertools?

At least that's our Q2 2017 roadmap.

There's really no sustainable future without closer coordination with AMBER developers. You previously indicated that a major change in the direction of AMBER development was unlikely, but given the new [MolSSI Institute](http://molssi.org/), there's now an opportunity for larger-scale coordination based on widely adopted best practices. 

Standardizing development and packaging practices is our best hope for a sustainable future, but how that will break down in terms of "carrot" (we'll give you money to adopt these practices) and "stick" (we will stop giving you money unless you adopt these practices) or somewhere in between is uncertain.

**Comment by hainm** [comment]
We have joint project with PHENIX team to use a part of AmberTools for crystal refinement.  So we (at least @dacase and me) are thinking about how to group packages into subpackages (like `ambermini`). But nothing is not yet. 

> There's really no sustainable future without closer coordination with AMBER developers.

this is a good idea.

**Comment by jchodera** [comment]
@hainm : Maybe we could we get someone from the Amber community involved in MolSSI, and maybe send someone from omnia out to the next Amber development meeting?

**Comment by hainm** [comment]
Alternatively, you can just build serial version of AmberTools and then use conda to copy needed folders
(e.g lib/, dat/, ...)

**Comment by hainm** [comment]
> maybe send someone from omnia out to the next Amber development meeting?

sounds a good plan for me. Amber Developers' Meeting will be held at in Athens, Georgia (at
the University of Georgia) February 15-17. Please send email to Dave about this.

**Comment by jchodera** [comment]
> Alternatively, you can just build serial version of AmberTools and then use conda to copy needed folders (e.g lib/, dat/, ...)

I think a number of tools had to be patched to fix the `AMBERHOME` environment variable requirement, like the [`tleap` script](https://github.com/choderalab/ambermini/blob/master/leap/tleap#L3).

If there was a way to build in `AMBERHOME`-independence into the main Amber development branch---such as automatic guessing of `AMBERHOME` based on the tool paths if the environment variable isn't set---then we could certainly adopt this strategy!

**Comment by hainm** [comment]
What's about
```bash
export AMBERHOME=`python -c 'import sys; print(sys.prefix)`
```

**Comment by Lnaden** [comment]
> `export AMBERHOME=`python -c 'import sys; print(sys.prefix)'`

That would work, but it makes 3 major assumptions that users may not want to always rely on: 
1. User sets the AMBERHOME variable in their `bashrc` or equivalent location
2. The user does not need/want AMBERHOME pointing at a full AmberTools install
3. User has their `python` command always pointing at their `conda` capable version

I can think of a number of cases where 1 and 2 especially are unfavored. Right now the custom binaries are wrappers which set the AMBERHOME variable at run time and point at the right location. To @swails point, there are parts of AmberTools which now require also setting `LD_LIBRARY_PATH` to point to AmberTools/lib, we don't need that for AmberMini right now, so thats not included, but it may be later.

I fully agree that this method of updating is really not sustainable due to how much manual checking of files is required. Without working closely with the AmberTools devs though, I don't see how we can reduce the pain of updating this package. Maybe convince them to create future versions that let you specify what tools to compile? That would simply the initial compile substantially.

**Comment by hainm** [comment]
> User sets the AMBERHOME variable in their bashrc or equivalent location

it's not really a bad idea :D. 

> The user does not need/want AMBERHOME pointing at a full AmberTools install
> User has their python command always pointing at their conda capable version

I meant about `ambermini`. You can compile some parts of AmberTools and then let conda to copy them to `$PREFIX/{bin,lib,dat...}`

> To @swails point, there are parts of AmberTools which now require also setting LD_LIBRARY_PATH to point to AmberTools/lib, we don't need that for AmberMini right now, so thats not included, but it may be later.

if you already copy files to `PREFIX/lib`, you do not need to set LD_LIBRARY_PATH since anaconda/miniconda already did that.

> Maybe convince them to create future versions that let you specify what tools to compile? That would simplify the initial compile substantially.

We have that (may be need to update a bit). Please check AmberTools/src/Makefile

**Comment by hainm** [comment]
we can also update that `Makefile` with something like

```bash
ambermini:: leap, sqm, antechamber
```

**Comment by swails** [comment]
Or you can just type `make leap sqm antechamber` -- the end goal should be to have the Amber team maintain its own pieces.  `ambermini` is starting to diverge a little too much, and I know the Amber devs won't want to be responsible for supporting splinters of the official distribution that they don't actually work on.

**Comment by swails** [comment]
The main idea behind ambermini is that it provides back-end engines for doing some small molecule parametrization tasks.  It's an implementation detail, which is why eliminating the need for setting `AMBERHOME` was considered important.

Users of the tools depending on ambermini should be considered ignorant of Amber altogether, so setting the variable `AMBERHOME` is confusing in this context (and difficult to do "correctly" in an automated capacity where installation locations may change).  That's why I bothered to make an environment variable-free scheme to run these tools (using wrapper scripts that set the variable for the underlying program based on the path of `$0`).

But it may be hard to convince Amber developers that an AMBERHOME-less execution mode is worth supporting.

**Comment by dacase** [comment]
Coming to this discussion late.  A few comments:

1. There seems to me to be a good use case for packaging and supporting a lighter subset of AmberTools that could be used for parameterization and system setup, but which is less tightly bound to the Amber MD engine.  (The name "amberlite" has been used internally in Amber, but I think we could repurpose it;  "ambermini" is obviously already taken....)  Working together on this makes sense to me, including getting omnia people to the Amber Developers' Meeting, or just setting up some in-person visits.

2. Re: the AMBERHOME environment variable: I don't understand how ambermini works now: is the installation location effectively hard-wired at install time?  If one wishes to deploy ambermini in lots of places, each with a different absolute tree structure, how does that work? The goal for the full AmberTools distribution has been that one could rsync the entire tree (including compiled executables) to a new location, change AMBERHOME to point there, and have everything work.  But in these days of conda and docker (etc.) we can certainly re-think all this.  Having the ability to not need AMBERHOME could/should be part of the core AmberTools code base, maintained by us.

3. (Slightly off-topic): we recognize that filenames relating to force fields were changed when Amber16 was released: the old situation was simply unsustainable. The days when one could talk about "the" Amber force field have gone away.  Our apologies for the changes, but tracking the new system is worth the effort.  [In the short term: the "oldff/leaprc.ff14SB" is identical to what was present in Amber14 in "leaprc.ff14SB".

**Comment by Lnaden** [comment]
> Working together on this makes sense to me, including getting omnia people to the Amber Developers' Meeting, or just setting up some in-person visits. 

I think getting a meeting together on this would be fantastic. I'm very much for having a subset of tools for just setup and parameterization would be very helpful. I can only speak for the projects I'm working on, so getting more people on this with other projects would be helpful.

>  I don't understand how ambermini works now: is the installation location effectively hard-wired at install time?

The way it works now is the actual binary which depends on AMBERHOME is compiled as `{binary name}_pvt` and then there is a wrapper script called `{binary name}` which is either shell or batch file that sets the AMBERHOME variable at runtime then invokes the `_pvt` binary. From the user perspective, there should be no difference.

> If one wishes to deploy ambermini in lots of places, each with a different absolute tree structure, how does that work?

Speaking for myself, and anyone please correct me if I am wrong as I'm still somewhat new to the dev of this. We deploy ambermini through a conda channel that points to the tarball releases here on GitHub. That way a user can just type `conda install -c omnia ambermini` which fetches and untars the tarball, runs the compile, delivers the binaries and their wrappers to a `bin` directory associated with that user's conda, so they can then run the ambermini binaries from command line freely. 

> we recognize that filenames relating to force fields were changed when Amber16 was released: 

That is fine. At some level we have to have the user recognize changes that are made to the code and its functionality. I spun off a specific AmberMini15 branch here on GitHub that we can push hotfixes to as needed for users who want to stay on the old version, but it wont receive the same attention as the master branch which is based on AmberTools 16+

**Comment by hainm** [comment]
> The way it works now is the actual binary which depends on AMBERHOME is compiled as {binary name}_pvt and then there is a wrapper script called {binary name} which is either shell or batch file that sets the AMBERHOME variable at runtime then invokes the _pvt binary. From the user perspective, there should be no difference.

so basically can we do this?
- download official AmberTools
- build corresponding packages (leap, sqm, ...)
- use conda to copy to `$PREFIX/{bin, lib, dat}`

@Dave: `$PREFIX` points to different Python env folder created by conda (`python -c 'import sys; print(sys.prefix)`)
- copy/make wrapper script to set AMBERHOME at run time.

**Comment by Lnaden** [comment]
> so basically can we do this?

I have generated a script which kind of does that. It will change a fair amount of how ambermini builds itself (also reducing size), but one problem it has is the tests all still have to be copied manually, along with re-writing most of the Makefiles

**Comment by Lnaden** [comment]
We also may want to move the "how do we handle ambermini going forward" conversation to its own thread

**Comment by swails** [comment]
The programs were replaced with scripts that call renamed programs (think tleap and teLeap). The scripts use the dirname of $0 to get the bin folder and sets AMBERHOME to dirname $0/.. before calling the actual program.

--
Jason M. Swails

**Comment by jchodera** [comment]
Migrate away from ambertools?

**Comment by Lnaden** [comment]
Question for the chat: Should we go ahead with this PR as is, open a new issue for handling build procedure going forward, and plan out what to do with this repo there? Or, should we try and handle the future builds in this PR?

**Comment by jchodera** [comment]
> Question for the chat: Should we go ahead with this PR as is, open a new issue for handling build procedure going forward, and plan out what to do with this repo there?

Yes! Save the future for another issue.

**Comment by Lnaden** [comment]
If there are no objections to this, I will merge it tomorrow, then open a new issue to handle this repo in the future.

**Pull request merged**
