### PR TITLE
At15

### PR DESCRIPTION
**Pull request by swails**
Updated from AmberTools 15.  Appears to work.

### CODE REVIEW

**Comment by jchodera** [comment]
Apologies for only getting around to commenting now!  

So many files have changed that it is probably best to merge and then do any cleanup from there.  Go ahead and merge when ready.

Are any patches applied to this version, or have none been released for AmberTools 15 yet?

**Comment by jchodera** [comment]
I'm assuming this is ready to merge!

**Comment by jchodera** [comment]
@swails: Have any patches been applied, or is this "stock"?

**Comment by swails** [comment]
Sorry, this was ready to merge.  I actually took it from the AmberTools 15 release branch which has all updates applied already.  (But no, I don't think any updates have targeted these programs, anyway).

**Pull request merged**
