### PR TITLE
antechamber -h should return 0

### LINKED ISSUE #22: ambermini conda package still failing
I'm still seeing a failure from the tests:
https://jenkins.choderalab.org/job/conda-omnia-release-osx-2/148/console

It gets as far as `tleap -h` now, so I'm guessing that this is returning a nonzero integer:
https://github.com/omnia-md/conda-recipes/blob/master/ambermini/meta.yaml#L20-L23

### PR DESCRIPTION
**Pull request by jchodera**
This fixes #22

### CODE REVIEW

**Comment by swails** [comment]
I'm confused.  This should be `tleap -h`, not `antechamber`, right?

**Comment by jchodera** [comment]
Yep, sorry.

**Comment by swails** [comment]
So this is something we should translate back to the AmberTools source code?

**Comment by jchodera** [comment]
Sure!  I just copied the change you had made last time:
https://github.com/choderalab/ambermini/commit/d3f76af1c3cd25425074c33a1116c5de49b8502c

**Comment by swails** [comment]
Done.

**Pull request merged**
