### PR TITLE
Support Windows [mingw]

### PR DESCRIPTION
**Pull request by rmcgibbo**
This was probably a mistake. It's working-ish though.

### CODE REVIEW

**Comment by jchodera** [comment]
Nice!  We don't have travis testing enabled here yet, it seems---someone should give this a try to make sure it still builds on linux?

**Comment by rmcgibbo** [comment]
Sure. I'd say for windows especially it's still WIP. I don't really have a test suite (I've been using the openmoltools tests, but they're not exhaustive).

**Comment by rmcgibbo** [comment]
The openmoltools tests (test_amber.py) do pass though.

**Comment by jchodera** [comment]
I have verified that this still compiles fine on Linux.

**Comment by swails** [comment]
Wait on merging this. I have to port this back to the main AmberTools repo or it will just be erased in April when Amber 16 is released. 

That's what happened last time around.

**Comment by rmcgibbo** [comment]
What is upstream AT policy w.r.t. windows?

**Comment by rmcgibbo** [comment]
Also, I think I can make this a little cleaner first.

**Comment by swails** [comment]
> What is upstream AT policy w.r.t. windows?

"What's Windows?"

**Comment by rmcgibbo** [comment]
Fair enough, but then are windows-specific changes like this going to be merged upstream?

**Comment by swails** [comment]
> Fair enough, but then are windows-specific changes like this going to be merged upstream?

Yes, I'll merge it upstream.  We don't go out of our way to break Windows, but we make no effort to support it (since nobody uses it in the dev community).  But we're more than happy to accept patches from others that makes it easier.

**Comment by rmcgibbo** [comment]
Okay. Let me clean it up bit first. I'll ping the thread when it's ready.

**Comment by rmcgibbo** [comment]
Kk. Cleaned up and rebased. I think this is good to go.

**Comment by jchodera** [comment]
Thanks!  I'll let @swails pull the trigger on this one since he noted:
> Wait on merging this.

**Comment by rmcgibbo** [comment]
I think you can just merge this and then @swails can merge it upstream at his convenience. We have the full git history, so nothing will be 'erased' either way.

**Comment by swails** [comment]
Merged upstream.  Not everything, but the leap changes in particular are there now.

The Makefile changes need to wait on defining `RM` in the configure script.  Thanks!

**Pull request merged**
